### ISSUE TITLE
Method anasol missing from API for PhysicsModel

### ISSUE THREAD

**Issue by keileg** [TheBB/Costa#11]
``In the IOT physical model, the physics based model is assumed to have a function `anasol`

https://github.com/TheBB/Costa/blob/d5b9aa2ec36168c05766f98581ffae4d15e7dff4/test/ifem-heateqn/published/iot-physical.py#L28

This is however not specified in API for PhysicsModels

https://github.com/TheBB/Costa/blob/d5b9aa2ec36168c05766f98581ffae4d15e7dff4/Costa/api.py#L16

I tried to find the implied method signature from the IFEM repository, but got lost in the class structure in that repo. Is it correct that the method implements something like

```python
def anasol(params: Dict[str, Union[float, List[float]]]) -> Dict[str, np.ndarray]):
    return {'primary': np.ndarray([values_given_information_from_params])
```

**Comment by akva2** [comment]
that is correct yes, it's a dict with [string : array-like] entries.

the name of the entries are a convention thing, you can do whatever you want as such, but in IFEM-CoSTA we use 'primary' and 'secondary_(x|y|z)'.

it's not in the PhysicsModel because it's not strictly necessary as such, just convenient for testing. I guess @TheBB forgot and stuck in in there without considering whether or not we should really require it.

**Comment by keileg** [comment]
Yes, a hack like that was mentioned. 

Thanks a lot, I will adjust my code accordingly.
